Working branch
edemagbenyo/images-videos-collins-edem pull request #1
Opened 2019-09-17 19:32 UTC by edemagbenyo

2019-09-18 00:26 UTC, uche-inyama requested changes
## Hi team :wave: nice work,

### However, there are some additions we need to make :smiley: 

- [ ] There are no linter checks on this project, also, you have to add .stickler.yml file to the root directory of this project and [use this information to configure your stickler.yml ](https://github.com/microverseinc/linters-config#linters-config). Go to [https://stickler-ci.com/](https://stickler-ci.com/) to sign up on stickler if you have not done so.

- [ ] Your README.md file is not detailed. Make it more descriptive, you can use this blue print.

     * A definition of this project
     * The authors of the project
     * Link to the **Clone**, you can use [Githack](https://raw.githack.com/) to get a link, by pasting the link of your html file from github on the field at **githack**
     * Also, you can provide a link to **Odin's project** for detailed information.


- [ ] There should be least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar, you have only.

- [ ] Below the Video section together with **like and dislike icons and share button**  there should be **an avatar** of the user who uploaded the video, you missed that.

### After implememting these changes, kindly submit another form for code review.

### This project is not approved :stop_sign:

2019-09-18 23:35 UTC, Redvanisation requested changes
### Hello @edemagbenyo and @collinsugwu  🌟 

**The project looks nice, however we need to implement some changes** ⬇️ 

1. The video is not well implemented on the page it must meet the following requirements: 
    - It is displayed
    -  It shows the video title
    -  It shows the number of views
2. Fix the number of views under the video.
3. Validate and fix the HTML markup: https://validator.w3.org/#validate_by_uri
4. Use Githack to create a live link for your project and put it in the README file after making the changes: https://raw.githack.com/

### _After finishing all the above changes please resubmit a code review request._

### Good luck guys! 🤞

2019-09-20 04:05 UTC, wathigo requested changes
## HI devs :wave: 
**Great work so far,** 
Before we give this a pass there are a few things you need to fix.
1. You CSS file has one error. Upload your code to [w3 validator](https://validator.w3.org/#validate_by_uri) and fix it.
2. There should be at least three embedded images at the right most part of the navigation bar. You only have two. Please add at least one. Also make sure the icons are aligned with the search bar.

**After implementing this changes, submit another request for review.**

_Good luck :)_

2019-09-21 02:43 UTC, bolah2009 requested changes
# Awesome job Team :clap: 

### The [clone](https://raw.githack.com/edemagbenyo/images-videos-collins-edem/824118b8536ac544166fdba27601a0bf501c58e3/index.html) looks good to me, uses HTML Video Embeding effectively. :clap: 

There are however a few required changes  to make the project even better  :blush:  :
 - Kindly rename the PR (to the name of the milestone) and the PR description to a brief summary of what was done in this PR. (Examples Below)
- Fix [HTML validation errors/warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fedemagbenyo%2Fimages-videos-collins-edem%2F824118b8536ac544166fdba27601a0bf501c58e3%2Findex.html), check comments for more details.
  > Validate your HTML markup with https://validator.w3.org/#validate_by_upload.

Kindly, check the comment below for suggestions.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-09-21 02:43 UTC, bolah2009 commented on index.html
> +            <img class="menu" src="./images/menu.png">
#### `HINT`

Please, always use `alt` attribute for `<img>` element. :bulb: 

This is a very important accessibility attribute.
**Examples of scenarios where users benefit from text alternatives for images** are listed below and could also be found [here](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

- They have a very slow connection and are browsing with images disabled.
- They have a vision impairment and use text to speech software.
- They have a cognitive impairment and use text to speech software.
- They are using a text-only browser.
- They are listening to the page being read out by a voice Web browser.
- They have images disabled to save on download costs.
- They have problems loading images or the source of an image is wrong.


##### SOURCE: [W3C Recommendation (Embedded Content)](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

2019-09-21 02:43 UTC, bolah2009 commented on README.md
> +
#### `OPTIONAL`

Nice job adding a descriptive readme.

Make it even more professional by adding the assignment link (from Odin),  screenshots of the page and what was learned during the project.

2019-09-21 02:44 UTC, bolah2009 reviewed
# Rename PR

  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)

-----

# Update PR description

  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-09-23 19:46 UTC, whiz25 approved these changes
## Awesome! :clap: 
Congratulations. You met all requirements for this project.
Please go ahead and merge and I wish you success in your next projects.

2019-09-23 19:49 UTC, merged